// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9HmJU2-5PuXQ3IlOxqEJ2YB4H6D0kqvQ',
    appId: '1:17681865839:web:89db41efbee9f587b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    authDomain: 'dqueue-716ad.firebaseapp.com',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    measurementId: 'G-XLVGTE34HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdAEa_YkPJ3oWpK-C2li6ftZ-SlVM_tKc',
    appId: '1:17681865839:android:4b592b84d1c54c24b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpd0-_wzQlwuGeHSyj6iucA1zDaFahYds',
    appId: '1:17681865839:ios:c08d90e5d54423a4b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    androidClientId: '17681865839-q903tdpev9q2ciar5ohel2poiae9l0df.apps.googleusercontent.com',
    iosClientId: '17681865839-jkm5h4ue7h1am6k18pbtcord00cnb3eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.dqApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpd0-_wzQlwuGeHSyj6iucA1zDaFahYds',
    appId: '1:17681865839:ios:c08d90e5d54423a4b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    androidClientId: '17681865839-q903tdpev9q2ciar5ohel2poiae9l0df.apps.googleusercontent.com',
    iosClientId: '17681865839-jkm5h4ue7h1am6k18pbtcord00cnb3eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.dqApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9HmJU2-5PuXQ3IlOxqEJ2YB4H6D0kqvQ',
    appId: '1:17681865839:web:71f4906f9fc83989b4019a',
    messagingSenderId: '17681865839',
    projectId: 'dqueue-716ad',
    authDomain: 'dqueue-716ad.firebaseapp.com',
    databaseURL: 'https://dqueue-716ad-default-rtdb.firebaseio.com',
    storageBucket: 'dqueue-716ad.appspot.com',
    measurementId: 'G-NB5NSPRLNN',
  );
}
